### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by woeterman94** [rahularyan/vote-smiley-reaction#7]
Are there any localisation options? I'd be happy to provide dutch translations if you explain me how to add them.

**Comment by rahularyan** [comment]
Yes, it is possible. You can visit this link for easy translation process https://translate.wordpress.org/projects/wp-plugins/vote-smiley-reaction/

Thanks for your contribution.

**Comment by woeterman94** [comment]
Do I need an invitation or how does that work?

**Comment by rahularyan** [comment]
You have to signup for a WordPress.org account if you don't have one. Please follow instructions here https://make.wordpress.org/polyglots/handbook/plugin-theme-authors-guide/pte-request/
Cheers!

**Comment by woeterman94** [comment]
Cool! Done. I added Dutch (Belgium). You can also use these under Dutch formal and Dutch (netherlands).
